# Generated by Django 5.1 on 2024-09-05 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_commande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='Zipcode',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='commande',
            name='Regions',
            field=models.CharField(default='Niamey', max_length=300),
        ),
    ]
